name: flutter_application_1
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  data_table_2: ^2.5.11
  dropdown_button2: 2.3.9
  fl_chart: ^0.66.2
  flutter_animate: ^4.5.0
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.1
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sqflite: ^2.3.2
  timeago: ^3.6.1
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2


dev_dependencies:
  flutter_lints: ^3.0.1
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  